version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: fitness_tracker_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fitness_tracker
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fitness_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fitness_tracker_app
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB_NAME=fitness_tracker
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL=300
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["--help"]

volumes:
  mongodb_data:
  redis_data:
